### ISSUE TITLE
requirements, pre-trained model and data link not working

### ISSUE THREAD

**Issue by guoyinwang** [ari-holtzman/l2w#1]
@ari-holtzman 
Hi,

I just try to follow the instruction to try code, but find some link not working on my side.

In the Requirement part, the instruction is "git clone git@github.com:pytorch/text.git", however, it gives the permission denied message. But I can directly using address "https://github.com/pytorch/text.git". So I think this part can be modified.

Also, the google drive link of pretrained model and data seems not working. The links show the files exist but cannot be downloaded or open due to re-direct problem. Would you mind double check this and update the link? 

Thanks,
Guoyin

**Comment by ari-holtzman** [comment]
Hi Guoyin,

To the cloning problem: it appears you have not setup `git` to work with `ssh`, but as you noted you can use the https link instead. I have changed the README to use https to avoid further confusion.

To the google drive link: I can view and download it even when I'm not signed-in, so I'm not sure what the problem you're having is. Is it possible the issue has something to do with your google accounts setup? Have you tried downloading when logged out of all google accounts (in an incognito window for instance)?

**Comment by guoyinwang** [comment]
Hi Ari,


Thanks very much for the reply. The issue is solved by switching from safari to chrome.


Best,

Guoyin

________________________________
